# Generated by Django 3.2.6 on 2021-08-20 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mainuser_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='imgs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
    ]
