# Generated by Django 3.2.6 on 2021-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_mainuser_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='imgs',
            field=models.ImageField(upload_to='main'),
        ),
    ]
