# Generated by Django 3.2.6 on 2021-08-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_mainuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='main'),
        ),
    ]
