# Generated by Django 3.2.6 on 2021-08-20 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_mainuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='main'),
            preserve_default=False,
        ),
    ]
