# Generated by Django 3.2.6 on 2021-08-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_mainuser_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='img',
            new_name='imgs',
        ),
    ]
